// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa4BcqE1niJapgOs2S9Iso1SVENyxnmcc',
    appId: '1:132665249373:web:eb21db0fec544c53fc87b4',
    messagingSenderId: '132665249373',
    projectId: 'zippo-bd662',
    authDomain: 'zippo-bd662.firebaseapp.com',
    storageBucket: 'zippo-bd662.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB2e0eIPY7Bk8KM2E9CWfmRQp5gDIDv3A',
    appId: '1:132665249373:android:d7f035b343ec7f3bfc87b4',
    messagingSenderId: '132665249373',
    projectId: 'zippo-bd662',
    storageBucket: 'zippo-bd662.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVNDrDuQt31TbL5aVdo6ZKpf5gztgu99g',
    appId: '1:132665249373:ios:025e9b279a18c45dfc87b4',
    messagingSenderId: '132665249373',
    projectId: 'zippo-bd662',
    storageBucket: 'zippo-bd662.appspot.com',
    androidClientId: '132665249373-j8tv10dq1e32ch442bkv1ncr13irbuav.apps.googleusercontent.com',
    iosClientId: '132665249373-r17b6k2pmua7a31tsjs2nievdrl043t0.apps.googleusercontent.com',
    iosBundleId: 'com.example.zippo',
  );
}
